### ISSUE TITLE
Increasing memory usage

### ISSUE THREAD

**Issue by alexmaco** [bvaisvil/zenith#33] opened 2020-05-05 05:19 UTC
Frequently, after using zenith for more than 24-28h memory usage follows a steady trend, reaching over 200MiB (used, not virtual) memory, as reported by zenith itself. This is not a sudden recent behavior, it has been there for at least one release.

Even when loading history, zenith starts at a much more reasonable ~18MiB.

[Here](https://gist.github.com/alexmaco/7a74e950108a0ad1d09a51c5fecbfb3a) are 2 memory profiles, that have run for over 24h. They were taken using valgrind's massif, with zenith built locally at d66adc51291

For viewing, massif-visualizer is a pretty good tool to explore the profiles.

**Comment by bvaisvil** [comment] 2020-05-05 16:22
Thanks a lot for running this. I'll take a look and see what I can do. I'm also happy to accept PRs if you find areas to optimize.

**Comment by alexmaco** [comment] 2020-05-05 16:58
Right now it looks like something originating from sysinfo, but it needs more investigation.

**Comment by bvaisvil** [comment] 2020-05-09 21:13
This was my conclusion looking at this as well. My hunch is that it's hanging onto all process data, including the dead ones. I thought the API had a `clear` function, but I'm not finding it now.

**Comment by Byron** [comment] 2020-06-05 04:48
I can reproduce this issue with zenith 0.9.2 (build from git) on MacOS. It became obvious that 'something' is happening when zenith would be gone every day, sometimes twice, with exit code 101. I suspected the OOM killer at work and started investigating.


After 9.5 minutes, it uses about 27MB of memory…
<img width="434" alt="Screenshot 2020-06-05 at 12 31 38" src="https://user-images.githubusercontent.com/63622/83837494-271e0d00-a729-11ea-8411-b45be74a8e64.png">

…and a minute later it's at nearly 32MB.
<img width="590" alt="Screenshot 2020-06-05 at 12 32 49" src="https://user-images.githubusercontent.com/63622/83837936-639e3880-a72a-11ea-8a3a-1ee9b173f211.png">

I tried again with the `--disable-history` flag, but it look like the trend prevails.

Using `Instruments` I was able to find a few allocation stacktraces that seemed to persist during the whole programs runtime, maybe this helps as a hint at where this is happening.

<img width="389" alt="Screenshot 2020-06-05 at 12 43 53" src="https://user-images.githubusercontent.com/63622/83838066-c8599300-a72a-11ea-96b3-9f791b67a702.png">
<img width="395" alt="Screenshot 2020-06-05 at 12 43 36" src="https://user-images.githubusercontent.com/63622/83838078-cd1e4700-a72a-11ea-89f0-02659984a8c1.png">
<img width="387" alt="Screenshot 2020-06-05 at 12 44 24" src="https://user-images.githubusercontent.com/63622/83838081-cee80a80-a72a-11ea-835d-766c2d178a56.png">
<img width="386" alt="Screenshot 2020-06-05 at 12 43 59" src="https://user-images.githubusercontent.com/63622/83838083-d0193780-a72a-11ea-989a-bd922cde5392.png">

**Comment by bvaisvil** [comment] 2020-06-05 22:14
Thanks for the info. What sort of memory usage have you seen on MacOS?

**Comment by Byron** [comment] 2020-06-06 01:39
I could never see the peak as all I got was zenith being gone the next morning. I think it's possible to extrapolate the memory usage though, for me it uses about 4MB per minute.

It will be very interesting to learn about the cause of this, just because thus far to me it seemed nigh impossible to leak memory in Rust unless cyclic data structures are used, memory is leaked intentionally or within a C library.

**Comment by alexmaco** [comment] 2020-06-06 10:46
@Byron It's great that you can reproduce it so reliably. On my machine the issue has stopped occurring in recent weeks, so I'm guessing it's related to the way processes come and go.

I've looked over the stacktraces you posted, but as far as i can tell all those allocations should be temporary, and should be freed on the next tick. It may be possible they look frequent because they are done all the time. Could you perhaps run zenith under valgrind with `--tool=massif` ? This will generate a history of allocs and frees that we can search for trends. If you are able to post the output of massif it would be much appreciated.

(note however valgrind+massif itself uses a lot more memory, so the oom kill may happen sooner)

Indeed, it's difficult to really leak memory in rust, but another possible scenario is accumulation, where instead there could be something like a data structure somewhere that continually grows, and is never cleared, so the memory could be accessible and not technically count as a leak but more like a logic error, similar to an infinite recursion that overflows the stack.

**Comment by alexmaco** [comment] 2020-06-06 11:16
@bvaisvil I notice that @Byron has also come across allocations coming from sysinfo. I see that the sysinfo version used in zenith is forked from an older point rather than using a recent one (which looks like it has had a lot of fixes and improvements).

Would it be possible to merge the changes required for zenith in the sysinfo upstream ? Or, alternatively, rebase sysinfo on top of master ? That way, these memory investigations will be more relevant.

**Comment by Byron** [comment] 2020-06-07 00:09
To get these tracebacks, I was using instruments. In there, it looked like this:

<img width="1097" alt="Screenshot 2020-06-07 at 08 03 07" src="https://user-images.githubusercontent.com/63622/83956914-65383f80-a895-11ea-989a-1fca529f2067.png">

It appears even though these allocations should be transient, they did indeed persist and were considered live and never destroyed (see the dropdown below saying "Created & Persistent").

In that long list, there is also the strack traces I posted, at least some of which seem to be related to drawing.

<img width="1097" alt="Screenshot 2020-06-07 at 08 04 50" src="https://user-images.githubusercontent.com/63622/83956929-97e23800-a895-11ea-82c7-c528fc8c5539.png">

Using valgrind would force me to use docker (the easiest way for me to get into a linux system), which seems like a big jump.

However, I am happy to try again whenever you want to validate changes in master, like updating to the latest version of sysinfo as suggested by @alexmaco .

Personally I can't wait to see this resolved, as now I am back to `bottom`, which gives me less relevant information, unfortunately.

**Comment by bvaisvil** [comment] 2020-06-07 17:02
In `sysinfo` there different code paths for MacOS and Linux. This suggests that the problem may not lie there. However, I'll work on updating `sysinfo` to see if that doesn't resolve the issue.

In my usage and testing, I haven't seen the same increasing memory usage over time on MacOS that I see on Linux. However, there is an occasional panic I do notice coming from `sysinfo`:
```
```

In any case, I agree it's time to update my fork to see if we don't see improvement.

**Comment by bvaisvil** [comment] 2020-06-07 17:54
Alright upon further testing I am to reproduce the memory increase on MacOS. I saw it peak at 300 MB in 20 mins.
Definitely very curious.

**Comment by bvaisvil** [comment] 2020-06-08 15:05
I made a new branch, [sysinfo_update](https://github.com/bvaisvil/zenith/tree/sysinfo_update). This uses the crates.io version of sysinfo. There are some fields missing (priority, nice, etc). And on linux, sysinfo has some parsing bugs which prevent it from correctly parsing information from some processes. 

However, on MacOS, I ran `valgrind --tool=massif` overnight (10 hours). I'm not an expert at reading massif output, so @alexmaco please let me know if I am mistaken, but it appears that the memory usage was very stable.

@Byron Valgrind appears tough to install on newer versions of MacOS, but I managed on 10.14.6 using this [repo](https://github.com/LouisBrunner/valgrind-macos) and this command:

```brew install --HEAD https://raw.githubusercontent.com/LouisBrunner/valgrind-macos/master/valgrind.rb```

[massif.out.74205.txt](https://github.com/bvaisvil/zenith/files/4746756/massif.out.74205.txt)

**Comment by alexmaco** [comment] 2020-06-08 19:33
@bvaisvil That looks very cool! Memory usage is almost flat in the file you posted, so it very much looks like sysinfo might have fixed the issue in the meantime. Looking forward to a master version with the updated library!

By the way, to avoid the need for recurring rebases in the future, would there be any issues with trying to merge the zenith-specific additions to master ? Ultimatelly, more systen information is something that sysinfo may be interested in, as long as it's done in a way that doesn't make the API very inconsistent or something.

**Comment by bvaisvil** [comment] 2020-06-08 20:31
> By the way, to avoid the need for recurring rebases in the future, would there be any issues with trying to merge the zenith-specific additions to master ? Ultimatelly, more systen information is something that sysinfo may be interested in, as long as it's done in a way that doesn't make the API very inconsistent or something.

Yes, definitely something I've planned on doing. It just was a matter of getting the time. It would also solve #5. 

I've attached massif on zenith 
[massif.out.30638.txt](https://github.com/bvaisvil/zenith/files/4748419/massif.out.30638.txt)
running for several hours, usage also looks flat there as well.

**Comment by Byron** [comment] 2020-06-09 07:57
Thanks so much for your efforts!

I have rebuilt from  8c7c497e6a5008b200c397ee17ade8030fe7e799, and the initial footprint was ~31MB, this is what I saw a few hours later.

<img width="588" alt="Screenshot 2020-06-09 at 15 42 10" src="https://user-images.githubusercontent.com/63622/84120574-987ef800-aa68-11ea-8fd9-02c42bbb4ca6.png">

The memory usage now was ~157MB. Right after seeing that I attached instruments and ran it for 3 minutes. It could still detect the occasional 'what seems to be a leak' allocation that did persist after having been created minutes earlier. Please note that these allocations are live according to instruments, even though they might usually be temporary.

<img width="959" alt="Screenshot 2020-06-09 at 15 43 03" src="https://user-images.githubusercontent.com/63622/84120622-aaf93180-aa68-11ea-9bdd-010eb418bb25.png">
<img width="976" alt="Screenshot 2020-06-09 at 15 43 09" src="https://user-images.githubusercontent.com/63622/84120625-ac2a5e80-aa68-11ea-864d-ea6bb2053ada.png">
<img width="966" alt="Screenshot 2020-06-09 at 15 42 58" src="https://user-images.githubusercontent.com/63622/84120611-a6347d80-aa68-11ea-84a3-7b277dbd4e13.png">

Please note even though it seems odd, especially since instruments doesn't recognize actual leaks, having these long-lived allocations is indeed real for zenith - another long-running program of mine, `criner`, only shows persistent allocations for the short moment it is drawing the TUI. The latter also shows the memory climbing radically and persisting in the moment libgit2 is used, and the C library never releases its memory despite the `Repository` instance already deallocated. Luckily it also doesn't cause more memory to be used the next time the repository is handled.

However, with the fix I would think that it has gotten better, and I will run it over night just to be sure.

**Comment by bvaisvil** [comment] 2020-06-09 18:42
@Byron Seems like the problem has not been solved for MacOS. I suppose I did not run it long enough. 

I like `heim` (and it's async API!), I use it for some features (CPU frequency, process management) but it isn't feature complete. I suppose, at this point process related field will need to be added to `heim` or `sysinfo`. The question is where it is most efficient to spend resources.

**Comment by Byron** [comment] 2020-06-10 01:37
@bvaisvil Actually that might not be entirely correct. This morning I did take another look and saw this:

<img width="632" alt="Screenshot 2020-06-10 at 09 30 23" src="https://user-images.githubusercontent.com/63622/84217031-ac286e00-aafd-11ea-85f9-1907a18c7390.png">

I will keep it running to see if it builds up again, as I am not entirely trusting my own testing methodology right now.

Thanks for sharing your thoughts on Heim - I was thinking that if it uses bindings to C less, that maybe it's less prone to leakage or memory corruption than sysinfo. Heim seemed to be a Rust rewrite, but that is more of a gut feeling than fact.

**Comment by Byron** [comment] 2020-06-10 07:24
<img width="576" alt="Screenshot 2020-06-10 at 15 23 16" src="https://user-images.githubusercontent.com/63622/84238965-633cdd80-ab2e-11ea-90c5-32d2267d9d84.png">

I think it's pretty clear that even though there is some buildup, it cleans itself after a while and most certainly is not a (severe) leak anymore 🎉.
Of course I will keep it running, but previously it didn't survive the night which already works just fine now.

**Comment by bvaisvil** [comment] 2020-06-11 03:45
Finished up the merge, the `master` branch now uses the new version of `sysinfo` with the changes for zenith. Please give it a try. I'm hoping that the memory usage profile remains unchanged from our previous testing. 

Either way, thanks for helping me out with this issue!

**Comment by Byron** [comment] 2020-06-11 11:52
<img width="582" alt="Screenshot 2020-06-11 at 19 50 35" src="https://user-images.githubusercontent.com/63622/84382161-d755af00-ac1c-11ea-82b4-70dc0ee19cf8.png">

Thank *you* for resolving it so quickly! By the looks of it, the leak(s) are gone, and I am back to `zenith` :).

**Comment by bvaisvil** [comment] 2020-06-11 15:24
Closing this as fixed, feel free to re-open if we have a regression!

**Closed by bvaisvil** 2020-06-11 15:24 UTC
Labels: bug
