### ISSUE TITLE
Arch Linux -- . zenith.lock 

### ISSUE THREAD

**Issue by dedguy21** [bvaisvil/zenith#17] opened 2020-03-28 06:18 UTC
Anytime I restart zenith I get an error advising me that the dot zenith dot lock file is still active even though I quit zenith or closed window.

And this happens even after reboot. It's not a huge problem rm .zenith.lock But it is a major annoyance and inconvenience.

Thanks. Really like this program.

**Comment by bvaisvil** [comment] 2020-03-28 16:35
Thanks for reporting! What version are you running? Did you install from an AUR?

**Comment by dedguy21** [comment] 2020-03-28 18:52
Yes I installed from AUR:
https://aur.archlinux.org/zenith.git

Which is the base version. (Not bin not git)

**Comment by bvaisvil** [comment] 2020-03-29 02:59
When you run `zenith -h`, which version does it say it is?

**Comment by dedguy21** [comment] 2020-03-29 19:17
version number is  zenith 0.7.7

**Comment by bvaisvil** [comment] 2020-03-29 21:58
Thanks. This definitely should not be happening. I just got an arch install and so far cannot reproduce.

How are you stopping zenith? Is it with a signal or 'q' or ? Could be there's a signal I'm not anticipating which then leaves the lock file around...

**Comment by bvaisvil** [comment] 2020-03-30 02:38
This [commit](https://github.com/bvaisvil/zenith/commit/975b734691e2030d303f743f9e85e8c7659a3cfd) adds support for other signals, including SIGTERM. That wasn't previously handled, so the lock file wouldn't be removed. Could you give this a try and see if it clears up your issue?

**Comment by dedguy21** [comment] 2020-03-30 18:00
Quiting with q. Also just closing terminal window. Either way the issue
occurs.

**Comment by dedguy21** [comment] 2020-03-30 21:55
Also I'm using both kitty and Alacritty terminal also AwesomeWM.

**Comment by bvaisvil** [comment] 2020-03-31 03:02
Thanks for the info. Could you try and build from the master branch and see if still have the issue?

**Comment by dedguy21** [comment] 2020-03-31 19:37
master git version works with no issue. I'll use that version

**Comment by bvaisvil** [comment] 2020-03-31 20:25
great, I'll publish it as 0.7.8, soon.

**Comment by bvaisvil** [comment] 2020-04-02 03:55
closing this, version 0.8.0 incorporates the fix.

**Closed by bvaisvil** 2020-04-02 03:55 UTC
Labels: bug
