### ISSUE TITLE
Long startup times due to 12GB database

### ISSUE THREAD

**Issue by Byron** [bvaisvil/zenith#12] opened 2020-03-22 13:05 UTC
When using zenith like I use bottom and let it run 24/7, I noticed that every morning the program seems to have aborted (without removing the lock).

That alone I was willing to ignore, but recently zenith didn't seem to startup anymore while using a lot of CPU and disk input.

When looking at the ~/.zenith folder, I saw this:

<img width="459" alt="Screenshot 2020-03-22 at 20 54 13" src="https://user-images.githubusercontent.com/63622/77249997-db0e1100-6c7f-11ea-8c54-1bf110584287.png">

This looks very familiar to me - it's a sled database. It will take a long time to open big databases, and depending on the way data is accessed, this included quite a sizeable amount of RAM usage.

Starting it with `zenith --disable-history` resolved the startup problem

### Meta

```
$ zenith --version
zenith 0.7.5
```

Tested on MacOS 10.15.3

**Comment by bvaisvil** [comment] 2020-03-22 14:41
Thanks for reporting. I thought I had fixed this bug. Did you compile from source or download one of the pre-compiled releases? If it was from source, please try the latest master branch and see if it doesn't trim the database.

**Comment by Byron** [comment] 2020-03-23 00:38
That's a great question! 

I checked and noticed that it is not on crates.io, so I believe I did install it from git at some point. Cargo seems to have forgotten about it, and when I update all installations, it's not even in the list.

I am now rebuilding from the latest master to retry. In anticipation of the issue being resolved as you suggest, I am happily closing this issue.

Thanks for your help!

**Comment by bvaisvil** [comment] 2020-03-23 02:41
I'm no longer convinced the issue is gone, actually. Might be related to https://github.com/filecoin-project/rust-fil-sector-builder/pull/71 and https://github.com/spacejam/sled/issues/786

**Comment by bvaisvil** [comment] 2020-03-25 02:28
Fixed in 0.7.6, decided to migrate to store the data on my own, not using sled, so this problem shouldn't re-occur. Zenith will also migrate the sled DB to it's own format on first run. However, if it is 12 GB...I'd probably just delete it :).

**Comment by Byron** [comment] 2020-03-25 02:44
Thank you:)!
And done! Personally I have no use of history on disk just yet, so start it with disable-history at all times.

**Closed** 2020-03-25 02:50 UTC
